package com.metcalf;

import org.joda.time.LocalDate;

public class Constants {
    public static final LocalDate SHIFTS_START_DATE = new LocalDate(2013, 12, 30);
    public static final Shift[] A_SHIFTS = {
            Shift.DAY,
            Shift.DAY,
            Shift.DAY,
            Shift.DAY,
            Shift.OFF,
            Shift.OFF,
            Shift.OFF,
            Shift.OFF,
            Shift.OFF,
            Shift.OFF,
            Shift.OFF,
            Shift.NIGHT,
            Shift.NIGHT,
            Shift.NIGHT,
            Shift.NIGHT,
            Shift.OFF,
            Shift.OFF,
            Shift.OFF,
            Shift.DAY,
            Shift.DAY,
            Shift.DAY,
            Shift.OFF,
            Shift.NIGHT,
            Shift.NIGHT,
            Shift.NIGHT,
            Shift.OFF,
            Shift.OFF,
            Shift.OFF,
    };
    public static final Shift[] C_SHIFTS = {
        Shift.NIGHT,
        Shift.OFF,
        Shift.OFF,
        Shift.OFF,
        Shift.DAY,
        Shift.DAY,
        Shift.DAY,
        Shift.OFF,
        Shift.NIGHT,
        Shift.NIGHT,
        Shift.NIGHT,
        Shift.OFF,
        Shift.OFF,
        Shift.OFF,
        Shift.DAY,
        Shift.DAY,
        Shift.DAY,
        Shift.DAY,
        Shift.OFF,
        Shift.OFF,
        Shift.OFF,
        Shift.OFF,
        Shift.OFF,
        Shift.OFF,
        Shift.OFF,
        Shift.NIGHT,
        Shift.NIGHT,
        Shift.NIGHT,
    };
}
